// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: customers_account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomerAccount = `-- name: CreateCustomerAccount :one
INSERT INTO customer_account(
    id,
    account_name,
    account_number,
    account_type,
    account_balance,
    initial_deposit,
    current_amount,
    customer_id,
    created_at,
    updated_at,
    is_deleted,
    deleted_at,
     currency_type,
    user_id,
    phone_number
)VALUES(
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15
)RETURNING id, account_name, account_number, account_type, currency_type, account_balance, initial_deposit, current_amount, customer_id, user_id, created_at, updated_at, is_deleted, deleted_at, phone_number
`

type CreateCustomerAccountParams struct {
	ID             uuid.UUID `json:"id"`
	AccountName    string    `json:"account_name"`
	AccountNumber  string    `json:"account_number"`
	AccountType    string    `json:"account_type"`
	AccountBalance string    `json:"account_balance"`
	InitialDeposit string    `json:"initial_deposit"`
	CurrentAmount  string    `json:"current_amount"`
	CustomerID     uuid.UUID `json:"customer_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IsDeleted      bool      `json:"is_deleted"`
	DeletedAt      time.Time `json:"deleted_at"`
	CurrencyType   string    `json:"currency_type"`
	UserID         uuid.UUID `json:"user_id"`
	PhoneNumber    string    `json:"phone_number"`
}

func (q *Queries) CreateCustomerAccount(ctx context.Context, arg CreateCustomerAccountParams) (CustomerAccount, error) {
	row := q.db.QueryRow(ctx, createCustomerAccount,
		arg.ID,
		arg.AccountName,
		arg.AccountNumber,
		arg.AccountType,
		arg.AccountBalance,
		arg.InitialDeposit,
		arg.CurrentAmount,
		arg.CustomerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDeleted,
		arg.DeletedAt,
		arg.CurrencyType,
		arg.UserID,
		arg.PhoneNumber,
	)
	var i CustomerAccount
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountNumber,
		&i.AccountType,
		&i.CurrencyType,
		&i.AccountBalance,
		&i.InitialDeposit,
		&i.CurrentAmount,
		&i.CustomerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const getCustomerAccount = `-- name: GetCustomerAccount :one
SELECT id, account_name, account_number, account_type, currency_type, account_balance, initial_deposit, current_amount, customer_id, user_id, created_at, updated_at, is_deleted, deleted_at, phone_number FROM customer_account WHERE id = $1
`

func (q *Queries) GetCustomerAccount(ctx context.Context, id uuid.UUID) (CustomerAccount, error) {
	row := q.db.QueryRow(ctx, getCustomerAccount, id)
	var i CustomerAccount
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountNumber,
		&i.AccountType,
		&i.CurrencyType,
		&i.AccountBalance,
		&i.InitialDeposit,
		&i.CurrentAmount,
		&i.CustomerID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const updateCustomerAccount = `-- name: UpdateCustomerAccount :exec
UPDATE customer_account SET
    account_balance= $1,
    initial_deposit= $2,
    current_amount= $3,
    updated_at = NOW()
WHERE id = $4
`

type UpdateCustomerAccountParams struct {
	AccountBalance string    `json:"account_balance"`
	InitialDeposit string    `json:"initial_deposit"`
	CurrentAmount  string    `json:"current_amount"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCustomerAccount(ctx context.Context, arg UpdateCustomerAccountParams) error {
	_, err := q.db.Exec(ctx, updateCustomerAccount,
		arg.AccountBalance,
		arg.InitialDeposit,
		arg.CurrentAmount,
		arg.ID,
	)
	return err
}
