// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: customers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerAccount = `-- name: CreateCustomerAccount :one
INSERT INTO customer_account(
    id,
    account_name,
    account_number,
    account_type,
    account_balance,
    initial_deposit,
    current_amount,
    customer_id,
    created_at,
    updated_at,
    is_deleted,
    deleted_at,
    phone_number
)VALUES(
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13
)RETURNING id, account_name, account_number, account_type, account_balance, initial_deposit, current_amount, customer_id, created_at, updated_at, is_deleted, deleted_at, phone_number
`

type CreateCustomerAccountParams struct {
	ID             uuid.UUID   `json:"id"`
	AccountName    string      `json:"account_name"`
	AccountNumber  string      `json:"account_number"`
	AccountType    string      `json:"account_type"`
	AccountBalance string      `json:"account_balance"`
	InitialDeposit string      `json:"initial_deposit"`
	CurrentAmount  string      `json:"current_amount"`
	CustomerID     pgtype.UUID `json:"customer_id"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	IsDeleted      bool        `json:"is_deleted"`
	DeletedAt      time.Time   `json:"deleted_at"`
	PhoneNumber    string      `json:"phone_number"`
}

func (q *Queries) CreateCustomerAccount(ctx context.Context, arg CreateCustomerAccountParams) (CustomerAccount, error) {
	row := q.db.QueryRow(ctx, createCustomerAccount,
		arg.ID,
		arg.AccountName,
		arg.AccountNumber,
		arg.AccountType,
		arg.AccountBalance,
		arg.InitialDeposit,
		arg.CurrentAmount,
		arg.CustomerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDeleted,
		arg.DeletedAt,
		arg.PhoneNumber,
	)
	var i CustomerAccount
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountNumber,
		&i.AccountType,
		&i.AccountBalance,
		&i.InitialDeposit,
		&i.CurrentAmount,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.PhoneNumber,
	)
	return i, err
}
