// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Otp struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Secret      string    `json:"secret"`
	IsVerified  bool      `json:"is_verified"`
	ExpiryTime  time.Time `json:"expiry_time"`
	VerfiedDate time.Time `json:"verfied_date"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	FullName     string    `json:"full_name"`
	Email        string    `json:"email"`
	Role         string    `json:"role"`
	Password     string    `json:"password"`
	Organization string    `json:"organization"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IsDeleted    bool      `json:"is_deleted"`
	DeletedAt    time.Time `json:"deleted_at"`
	PhoneNumber  string    `json:"phone_number"`
	ProfilePic   string    `json:"profile_pic"`
	UserStatus   bool      `json:"user_status"`
	IsVerified   bool      `json:"is_verified"`
	ApiKey       string    `json:"api_key"`
}
