// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ForgetPassword(ctx context.Context, arg ForgetPasswordParams) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetOTPByUserID(ctx context.Context, userID uuid.UUID) (Otp, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (GetUserByPhoneNumberRow, error)
	UpdateOTP(ctx context.Context, arg UpdateOTPParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) error
	UpdateUserbyAdmin(ctx context.Context, arg UpdateUserbyAdminParams) error
	UserStatusUpdate(ctx context.Context, arg UserStatusUpdateParams) error
}

var _ Querier = (*Queries)(nil)
